version: '3.8'

services:
  # 1. Database - Stores Problems, Users, Submission Results
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: judge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Message Queue - Queues up code submissions
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   # Main port for communication
      - "15672:15672" # Management Dashboard (UI)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  # 3. Cache - Stores live status and temp data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: